name 'cleanwater'
maintainer 'Helior Colorado'
maintainer_email 'me@helior.info'
license 'All rights reserved'
description 'Install & configure a Drupal-ready server'
version IO.read(File.join(File.dirname(__FILE__), 'VERSION')) rescue '0.0.1'
